# Generated by Django 2.2.5 on 2021-08-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prediction1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.FloatField(max_length=5)),
                ('Year', models.FloatField(max_length=5)),
                ('Kilometers_Driven', models.FloatField(max_length=5)),
                ('Fuel_Type', models.FloatField(max_length=5)),
                ('Transmission', models.FloatField(max_length=5)),
                ('Owner_Type', models.FloatField(max_length=5)),
                ('Mileage', models.FloatField(max_length=5)),
                ('Engine', models.FloatField(max_length=5)),
                ('Power', models.FloatField(max_length=5)),
                ('Seats', models.FloatField(max_length=5)),
            ],
        ),
    ]
