# Generated by Django 3.2.6 on 2021-08-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210810_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction1',
            name='Engine',
            field=models.FloatField(max_length=128),
        ),
        migrations.AlterField(
            model_name='prediction1',
            name='Fuel_Type',
            field=models.CharField(choices=[('CNG', 'CNG'), ('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=128),
        ),
        migrations.AlterField(
            model_name='prediction1',
            name='Kilometers_Driven',
            field=models.FloatField(max_length=128),
        ),
        migrations.AlterField(
            model_name='prediction1',
            name='Mileage',
            field=models.FloatField(max_length=128),
        ),
        migrations.AlterField(
            model_name='prediction1',
            name='Name',
            field=models.CharField(choices=[('Audi A4 35 TDI Technology', 'Audi A4 35 TDI Technology'), ('Skoda Octavia 2.0 TDI MT Style', 'Skoda Octavia 2.0 TDI MT Style'), ('Maruti Baleno Alpha', 'Maruti Baleno Alpha'), ('Honda BR-V i-VTEC VX MT', 'Honda BR-V i-VTEC VX MT'), ('Mercedes-Benz GLE 350d', 'Mercedes-Benz GLE 350d'), ('Honda Brio 1.2 S MT', 'Honda Brio 1.2 S MT'), ('Maruti Baleno Delta CVT', 'Maruti Baleno Delta CVT'), ('Mitsubishi Pajero Sport 4X2 AT', 'Mitsubishi Pajero Sport 4X2 AT'), ('Toyota Etios Cross 1.2L G', 'Toyota Etios Cross 1.2L G'), ('Maruti Wagon R VXI 1.2', 'Maruti Wagon R VXI 1.2'), ('Hyundai Grand i10 1.2 Kappa Sportz AT', 'Hyundai Grand i10 1.2 Kappa Sportz AT'), ('Toyota Camry Hybrid 2.5', 'Toyota Camry Hybrid 2.5'), ('Ford EcoSport 1.5 Diesel Titanium', 'Ford EcoSport 1.5 Diesel Titanium'), ('Mini Cooper 3 DOOR D', 'Mini Cooper 3 DOOR D'), ('Hyundai Grand i10 1.2 CRDi Magna', 'Hyundai Grand i10 1.2 CRDi Magna'), ('Renault Duster 110PS Diesel RxZ AMT', 'Renault Duster 110PS Diesel RxZ AMT'), ('Hyundai Elantra 2.0 SX Option AT', 'Hyundai Elantra 2.0 SX Option AT'), ('Fiat Avventura Urban Cross 1.3 Multijet Emotion', 'Fiat Avventura Urban Cross 1.3 Multijet Emotion'), ('Mahindra Xylo D4', 'Mahindra Xylo D4'), ('Volkswagen Vento 1.6 Trendline', 'Volkswagen Vento 1.6 Trendline'), ('Mini Clubman Cooper S', 'Mini Clubman Cooper S'), ('Mercedes-Benz GLC 220d 4MATIC Sport', 'Mercedes-Benz GLC 220d 4MATIC Sport'), ('Tata Tiago 1.2 Revotron XT Option', 'Tata Tiago 1.2 Revotron XT Option'), ('Ford Freestyle Titanium Plus Diesel', 'Ford Freestyle Titanium Plus Diesel'), ('Maruti Dzire AMT VDI', 'Maruti Dzire AMT VDI'), ('Maruti Dzire AMT ZXI Plus', 'Maruti Dzire AMT ZXI Plus'), ('Maruti Wagon R VXI AMT Opt', 'Maruti Wagon R VXI AMT Opt'), ('Skoda Rapid 1.6 MPI Ambition', 'Skoda Rapid 1.6 MPI Ambition'), ('Honda City i-VTEC VX', 'Honda City i-VTEC VX'), ('Mahindra Verito 1.5 D4 BSIV', 'Mahindra Verito 1.5 D4 BSIV'), ('Toyota Innova Crysta 2.8 ZX AT', 'Toyota Innova Crysta 2.8 ZX AT'), ('Mahindra Bolero Power Plus ZLX', 'Mahindra Bolero Power Plus ZLX'), ('Tata Tiago 1.05 Revotorq XT Option', 'Tata Tiago 1.05 Revotorq XT Option'), ('Datsun GO T Petrol', 'Datsun GO T Petrol'), ('Jaguar XE 2.0L Diesel Prestige', 'Jaguar XE 2.0L Diesel Prestige'), ('Nissan Micra Active XV', 'Nissan Micra Active XV'), ('Hyundai Verna CRDi 1.6 SX Option', 'Hyundai Verna CRDi 1.6 SX Option'), ('Mahindra Bolero SLX', 'Mahindra Bolero SLX'), ('Maruti Ignis 1.2 AMT Delta', 'Maruti Ignis 1.2 AMT Delta'), ('Maruti Celerio X VXI Option', 'Maruti Celerio X VXI Option'), ('Nissan Terrano XV D Pre', 'Nissan Terrano XV D Pre'), ('Hyundai Xcent 1.2 CRDi SX', 'Hyundai Xcent 1.2 CRDi SX'), ('Maruti Vitara Brezza ZDi Plus AMT', 'Maruti Vitara Brezza ZDi Plus AMT'), ('Fiat Linea Classic 1.3 Multijet', 'Fiat Linea Classic 1.3 Multijet'), ('Datsun redi-GO T Option', 'Datsun redi-GO T Option'), ('Maruti Vitara Brezza ZDi Plus Dual Tone', 'Maruti Vitara Brezza ZDi Plus Dual Tone'), ('Maruti Dzire VXI', 'Maruti Dzire VXI'), ('Fiat Punto EVO 1.3 Emotion', 'Fiat Punto EVO 1.3 Emotion'), ('Hyundai i20 Active SX Diesel', 'Hyundai i20 Active SX Diesel'), ('Toyota Etios Cross 1.4L VD', 'Toyota Etios Cross 1.4L VD'), ('Skoda Rapid 1.6 MPI AT Style', 'Skoda Rapid 1.6 MPI AT Style'), ('Bentley Flying Spur W12', 'Bentley Flying Spur W12'), ('Hyundai Verna VTVT 1.6 AT SX Option', 'Hyundai Verna VTVT 1.6 AT SX Option'), ('Toyota Etios Liva 1.4 VXD', 'Toyota Etios Liva 1.4 VXD'), ('Jaguar XE Portfolio', 'Jaguar XE Portfolio'), ('Skoda Superb Style 1.8 TSI AT', 'Skoda Superb Style 1.8 TSI AT'), ('Mahindra KUV 100 G80 K4 Plus 5Str', 'Mahindra KUV 100 G80 K4 Plus 5Str'), ('Hyundai Creta 1.6 SX Automatic Diesel', 'Hyundai Creta 1.6 SX Automatic Diesel'), ('Toyota Innova Crysta 2.4 VX MT 8S', 'Toyota Innova Crysta 2.4 VX MT 8S'), ('Tata Zest Quadrajet 1.3 75PS XE', 'Tata Zest Quadrajet 1.3 75PS XE'), ('Maruti Wagon R LXI', 'Maruti Wagon R LXI'), ('Honda Jazz VX CVT', 'Honda Jazz VX CVT'), ('Maruti Wagon R VXI AMT', 'Maruti Wagon R VXI AMT'), ('Mahindra Verito Vibe 1.5 dCi D6', 'Mahindra Verito Vibe 1.5 dCi D6'), ('Datsun GO Plus T Petrol', 'Datsun GO Plus T Petrol'), ('Maruti Alto K10 LXI CNG Optional', 'Maruti Alto K10 LXI CNG Optional'), ('Honda City i-DTEC SV', 'Honda City i-DTEC SV'), ('Jeep Compass 2.0 Longitude', 'Jeep Compass 2.0 Longitude'), ('Hyundai Elite i20 Magna Plus', 'Hyundai Elite i20 Magna Plus'), ('BMW 5 Series 530i Sport Line', 'BMW 5 Series 530i Sport Line'), ('Hyundai Grand i10 1.2 CRDi Sportz', 'Hyundai Grand i10 1.2 CRDi Sportz'), ('Toyota Innova Crysta 2.8 GX AT', 'Toyota Innova Crysta 2.8 GX AT'), ('Audi Q3 30 TDI Premium FWD', 'Audi Q3 30 TDI Premium FWD'), ('Mercedes-Benz B Class B180 Sport', 'Mercedes-Benz B Class B180 Sport'), ('Tata Zest Revotron 1.2T XE', 'Tata Zest Revotron 1.2T XE'), ('Mercedes-Benz SLC 43 AMG', 'Mercedes-Benz SLC 43 AMG'), ('Volkswagen Vento 1.5 TDI Highline', 'Volkswagen Vento 1.5 TDI Highline'), ('Tata Tiago 1.2 Revotron XZ', 'Tata Tiago 1.2 Revotron XZ'), ('Hyundai Verna VTVT 1.6 SX', 'Hyundai Verna VTVT 1.6 SX'), ('Tata Tiago 1.2 Revotron XT', 'Tata Tiago 1.2 Revotron XT'), ('Renault KWID Climber 1.0 AMT', 'Renault KWID Climber 1.0 AMT'), ('Nissan Micra XV CVT', 'Nissan Micra XV CVT'), ('Maruti Ignis 1.2 Delta', 'Maruti Ignis 1.2 Delta'), ('Toyota Fortuner 2.8 2WD MT', 'Toyota Fortuner 2.8 2WD MT'), ('Maruti Swift VDI', 'Maruti Swift VDI'), ('Maruti Vitara Brezza ZDi', 'Maruti Vitara Brezza ZDi'), ('Honda Brio 1.2 VX MT', 'Honda Brio 1.2 VX MT'), ('Maruti Ignis 1.2 Alpha', 'Maruti Ignis 1.2 Alpha'), ('Renault Duster 85PS Diesel RxZ', 'Renault Duster 85PS Diesel RxZ'), ('Jaguar XF 2.0 Petrol Portfolio', 'Jaguar XF 2.0 Petrol Portfolio'), ('Mitsubishi Pajero Sport 4X4', 'Mitsubishi Pajero Sport 4X4'), ('Maruti Vitara Brezza LDi', 'Maruti Vitara Brezza LDi'), ('Honda WRV i-DTEC VX', 'Honda WRV i-DTEC VX'), ('Hyundai Creta 1.6 SX Automatic', 'Hyundai Creta 1.6 SX Automatic'), ('Honda BRV i-VTEC V CVT', 'Honda BRV i-VTEC V CVT'), ('Hyundai Creta 1.6 SX Diesel', 'Hyundai Creta 1.6 SX Diesel'), ('Jeep Compass 1.4 Sport', 'Jeep Compass 1.4 Sport'), ('Honda BR-V i-DTEC S MT', 'Honda BR-V i-DTEC S MT'), ('Maruti Baleno Delta', 'Maruti Baleno Delta'), ('Mercedes-Benz E-Class E 220 d', 'Mercedes-Benz E-Class E 220 d'), ('Mercedes-Benz GLA Class 220 d 4MATIC', 'Mercedes-Benz GLA Class 220 d 4MATIC'), ('Honda BRV i-DTEC V MT', 'Honda BRV i-DTEC V MT'), ('Mercedes-Benz GLE 250d', 'Mercedes-Benz GLE 250d'), ('Audi A4 35 TDI Premium Plus', 'Audi A4 35 TDI Premium Plus'), ('Mahindra Bolero ZLX', 'Mahindra Bolero ZLX'), ('Jeep Compass 2.0 Sport', 'Jeep Compass 2.0 Sport'), ('Maruti Dzire ZDI', 'Maruti Dzire ZDI'), ('BMW 3 Series Luxury Line', 'BMW 3 Series Luxury Line'), ('Maruti Alto K10 LXI', 'Maruti Alto K10 LXI'), ('Maruti Alto K10 VXI', 'Maruti Alto K10 VXI'), ('Hyundai Grand i10 1.2 Kappa Sportz', 'Hyundai Grand i10 1.2 Kappa Sportz'), ('Toyota Innova Crysta 2.4 ZX MT', 'Toyota Innova Crysta 2.4 ZX MT'), ('Volkswagen Ameo 1.5 TDI Highline', 'Volkswagen Ameo 1.5 TDI Highline'), ('Ford EcoSport 1.5 Petrol Ambiente', 'Ford EcoSport 1.5 Petrol Ambiente'), ('Hyundai Tucson 2.0 e-VGT 4WD AT GLS', 'Hyundai Tucson 2.0 e-VGT 4WD AT GLS'), ('Renault KWID RXL', 'Renault KWID RXL'), ('Toyota Innova Crysta Touring Sport 2.4 MT', 'Toyota Innova Crysta Touring Sport 2.4 MT'), ('Hyundai Verna CRDi 1.6 AT SX Plus', 'Hyundai Verna CRDi 1.6 AT SX Plus'), ('Mahindra KUV 100 D75 K8 5Str', 'Mahindra KUV 100 D75 K8 5Str'), ('Maruti Ertiga VXI Petrol', 'Maruti Ertiga VXI Petrol'), ('Hyundai Elantra 1.6 SX', 'Hyundai Elantra 1.6 SX'), ('Hyundai Elite i20 Asta Option', 'Hyundai Elite i20 Asta Option'), ('Jeep Compass 2.0 Limited Option 4X4', 'Jeep Compass 2.0 Limited Option 4X4'), ('Maruti Wagon R VXI', 'Maruti Wagon R VXI'), ('Hyundai Grand i10 1.2 Kappa Magna', 'Hyundai Grand i10 1.2 Kappa Magna'), ('Volkswagen Ameo 1.5 TDI Comfortline', 'Volkswagen Ameo 1.5 TDI Comfortline'), ('Hyundai Xcent 1.2 VTVT E', 'Hyundai Xcent 1.2 VTVT E'), ('Toyota Corolla Altis 1.8 G', 'Toyota Corolla Altis 1.8 G'), ('Skoda Superb L&K 2.0 TDI AT', 'Skoda Superb L&K 2.0 TDI AT'), ('Skoda Rapid 1.5 TDI AT Ambition', 'Skoda Rapid 1.5 TDI AT Ambition'), ('Tata Tiago AMT 1.2 Revotron XTA', 'Tata Tiago AMT 1.2 Revotron XTA'), ('Maruti Eeco 5 Seater AC', 'Maruti Eeco 5 Seater AC'), ('Maruti Alto LXI', 'Maruti Alto LXI'), ('BMW 5 Series 520d Luxury Line', 'BMW 5 Series 520d Luxury Line'), ('BMW 7 Series 730Ld DPE Signature', 'BMW 7 Series 730Ld DPE Signature'), ('Audi Q3 35 TDI Quattro Premium Plus', 'Audi Q3 35 TDI Quattro Premium Plus'), ('Toyota Innova Crysta 2.8 GX AT 8S', 'Toyota Innova Crysta 2.8 GX AT 8S'), ('Honda City i-VTEC CVT ZX', 'Honda City i-VTEC CVT ZX'), ('Tata Tiago 1.2 Revotron XZ WO Alloy', 'Tata Tiago 1.2 Revotron XZ WO Alloy'), ('Volkswagen Vento 1.5 TDI Highline Plus AT', 'Volkswagen Vento 1.5 TDI Highline Plus AT'), ('Mahindra Thar CRDe', 'Mahindra Thar CRDe'), ('Maruti Vitara Brezza ZDi AMT', 'Maruti Vitara Brezza ZDi AMT'), ('Audi A6 35 TDI Matrix', 'Audi A6 35 TDI Matrix')], max_length=128),
        ),
        migrations.AlterField(
            model_name='prediction1',
            name='Owner_Type',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second')], max_length=128),
        ),
        migrations.AlterField(
            model_name='prediction1',
            name='Power',
            field=models.FloatField(max_length=128),
        ),
        migrations.AlterField(
            model_name='prediction1',
            name='Seats',
            field=models.FloatField(max_length=128),
        ),
        migrations.AlterField(
            model_name='prediction1',
            name='Transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=128),
        ),
        migrations.AlterField(
            model_name='prediction1',
            name='Year',
            field=models.FloatField(max_length=128),
        ),
        migrations.AlterField(
            model_name='prediction1',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
